export const TOGGLE_POPUP = "TOGGLE_POPUP";
export const TOGGLE_SIGNUP_POPUP = "TOGGLE_SIGNUP_POPUP";

export const OPEN_POPUP = "OPEN_POPUP";
export const CLOSE_POPUP = "CLOSE_POPUP";

export const OPEN_SIGNUP_POPUP = "OPEN_SIGNUP_POPUP";
export const CLOSE_SIGNUP_POPUP = "CLOSE_SIGNUP_POPUP";

export const OPEN_EDIT_POPUP = "OPEN_EDIT_POPUP";
export const CLOSE_EDIT_POPUP = "CLOSE_EDIT_POPUP";

export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";

export const SIGNUP = "SIGNUP";

export const SET_LOGGED_IN_USER = "SET_LOGGED_IN_USER";
export const DEL_LOGGED_IN_USER = "DEL_LOGGED_IN_USER";

export const DATA_LOADING_TRUE = "DATA_LOADING_TRUE";
export const DATA_LOADING_FALSE = "DATA_LOADING_FALSE";
